### ISSUE TITLE
tools added to workflow should not be embedded by default

### ISSUE THREAD

**Issue by mr-c** [rabix/composer#252]
They should be referenced with `run` especially if they are from the same workspace directory

**Comment by mr-c** [comment]
Hmm.. now it is using references. Odd.

**Comment by mayacoda** [comment]
@mr-c, the composer only embeds apps in workflows if the workflow belongs to a SevenBridges platform or is being saved there (pushing a local workflow, for example). Otherwise, references to the will be used. However, for the time being these references are absolute paths, so it might have unexpected results if you're using git to collaborate on a workflow, for example.
