### ISSUE TITLE
Execution error on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by sjaenick** [rabix/composer#450]
Tried to run the 1.0.1 and 1.0.2 AppImages, which both worked fine up to Ubuntu xenial; with
Ubuntu 20.04 LTS (focal), both fail for me with the same error message:

```
$ ./rabix-composer.1.0.2.AppImage

(rabix-composer:12149): Pango-ERROR **: 14:52:04.892: Harfbuzz version too old (1.4.2)

Trace/breakpoint trap
```

**Comment by sjaenick** [comment]
related:
https://github.com/electron/electron/issues/20348

**Comment by kaushik-work** [comment]
Hi @marijanlekic , could you take a look at this? Thank you!

**Comment by aleferna** [comment]
same problem here

**Comment by kaushik-work** [comment]
Hi @sjaenick , @aleferna sorry you are facing these problems. We are likely staffed to work on a new release in July. I'm hoping we can update the build system and dependencies during this process.

In the meanwhile, would it be possible for you to compile from source? We've updated the install instructions because the code is currently finicky about node version.

**Comment by aleferna** [comment]
HI, I tried rebuilding from source but I got the same error message?

**Comment by milosdanilov** [comment]
@aleferna @sjaenick We are working on update to new major electron version. And waiting on the release of new electron version for support, in order to resolve this error. 

In the meantime, try:
- https://github.com/electron/electron/issues/20348#issuecomment-562112996
- https://github.com/electron/electron/issues/20348#issuecomment-635378964

**Comment by cccnrc** [comment]
same error

**Comment by pmiddend** [comment]
Yes, this is still not solved. Has work on the project stalled?
